import "../styles/ReasoningTrace.css";
import { getAction } from "../constants";

const DIFF_LABEL = { 1: "⭐ Beginner", 2: "⭐⭐ Intermediate", 3: "⭐⭐⭐ Intermediate+", 4: "⭐⭐⭐⭐ Advanced", 5: "⭐⭐⭐⭐⭐ Expert" };

export default function ReasoningTrace({ step }) {
  if (!step) {
    return (
      <div className="reasoning-trace">
        <span className="trace-empty-icon">🔍</span>
        <div className="trace-empty">
          <p>Click any module in the pathway to see the AI reasoning trace explaining why it was included, skipped, or fast-tracked.</p>
        </div>
      </div>
    );
  }

  const cfg    = getAction(step.action);
  const curPct = Math.round((step.proficiency_current  || 0) * 100);
  const reqPct = Math.round((step.proficiency_required || 0) * 100);
  const isSkip = step.action === "SKIP";
  const conf   = Math.round((step.confidence || 0.75) * 100);

  return (
    <div className="reasoning-trace" style={{ borderColor: `${cfg.color}25` }}>

      {/* Tag */}
      <div className="trace-tag" style={{ color: cfg.color }}>🔍 Reasoning Trace</div>

      {/* Module name */}
      <div className="trace-module-name">{step.module_name}</div>

      {/* Domain + difficulty row */}
      {(step.domain || step.difficulty) && (
        <div className="trace-meta-row">
          {step.domain && (
            <span className="trace-domain-tag">{step.domain}</span>
          )}
          {step.difficulty && (
            <span className="trace-diff-tag">{DIFF_LABEL[step.difficulty] ?? ""}</span>
          )}
        </div>
      )}

      {/* Proficiency bars */}
      <div className="trace-proficiency">
        <ProfBar label="Your level" pct={curPct} color="#FF5C3A" />
        <ProfBar label="Required"   pct={reqPct} color={cfg.color} />
      </div>

      {/* Action badge */}
      <div
        className="trace-action-badge"
        style={{ background: cfg.bgColor, color: cfg.color, border: `1px solid ${cfg.border}` }}
      >
        {step.action.replace("_", "-")}
      </div>

      {/* AI-generated reason */}
      <p className="trace-reason" style={{ borderLeftColor: cfg.color }}>
        {step.reason || "Reasoning trace generated by AI based on your proficiency gap."}
      </p>

      {/* Time + savings row */}
      <div className="trace-time-card">
        <span className="trace-time-label">Estimated time</span>
        <span className="trace-time-val" style={{ color: cfg.color }}>
          {isSkip ? "0h (skipped)" : `${step.estimated_hours}h`}
        </span>
      </div>
      {step.hours_saved > 0 && (
        <div className="trace-time-card" style={{ marginTop: "0.4rem" }}>
          <span className="trace-time-label">⚡ Time saved</span>
          <span className="trace-time-val" style={{ color: "#c8f53c" }}>
            {step.hours_saved}h vs traditional
          </span>
        </div>
      )}

      {/* Confidence */}
      <div className="trace-time-card" style={{ marginTop: "0.4rem" }}>
        <span className="trace-time-label">Confidence</span>
        <span className="trace-time-val" style={{ color: cfg.color }}>{conf}%</span>
      </div>

      {/* Score breakdown (collapsible) */}
      {step.score_breakdown && Object.keys(step.score_breakdown).length > 0 && (
        <details className="trace-breakdown">
          <summary>Scoring breakdown</summary>
          <div className="trace-breakdown-grid">
            {Object.entries(step.score_breakdown)
              .filter(([k]) => k !== "final_score")
              .map(([k, v]) => (
                <div key={k} className="trace-breakdown-row">
                  <span>{k.replace(/_/g, " ")}</span>
                  <span>{typeof v === "number" ? v.toFixed(3) : v}</span>
                </div>
              ))}
          </div>
        </details>
      )}

      {/* Prerequisites */}
      {step.prerequisites?.length > 0 && (
        <div>
          <div className="trace-prereqs-label">Prerequisites</div>
          <div className="trace-prereqs-list">
            {step.prerequisites.map((p) => (
              <span key={p} className="trace-prereq-tag">{p}</span>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

function ProfBar({ label, pct, color }) {
  return (
    <div className="trace-prof-row">
      <div className="trace-prof-label-row">
        <span>{label}</span>
        <span className="trace-prof-pct" style={{ color }}>{pct}%</span>
      </div>
      <div className="trace-prof-bar">
        <div className="trace-prof-fill" style={{ width: `${pct}%`, background: color }} />
      </div>
    </div>
  );
}
